export const ErrorMessages = {
  INVALID_PAYLOAD: 'INVALID_PAYLOAD',

  MAX_AMOUNT_IN_CART_EXCEEDED: 'MAX_AMOUNT_IN_CART_EXCEEDED',
  MAX_DIGITAL_ITEM_EXCEEDED: 'MAX_DIGITAL_ITEM_EXCEEDED',
  MAX_ALLOWED_QUANTITY_IN_CART_EXCEEDED: 'MAX_ALLOWED_QUANTITY_IN_CART_EXCEEDED',
  MAX_UNIQUE_TEM_COUNT_IN_CART_EXCEEDED: 'MAX_UNIQUE_TEM_COUNT_IN_CART_EXCEEDED',

  ITEM_NOT_FOUND_TO_REMOVE: 'ITEM_NOT_FOUND_TO_REMOVE',
  VAS_ITEM_NOT_FOUND_TO_REMOVE: 'VAS_ITEM_NOT_FOUND_TO_REMOVE',
  MAX_ALLOWED_VAS_QUANTITY_EXCEEDED_IN_DEFAULT_ITEM: 'MAX_ALLOWED_VAS_QUANTITY_EXCEEDED_IN_DEFAULT_ITEM',
  MAX_ALLOWED_VAS_QUANTITY_EXCEEDED_IN_CART: 'MAX_ALLOWED_VAS_QUANTITY_EXCEEDED_IN_CART',
  MAX_ALLOWED_QUANTITY_VALUE_EXCEEDED_FOR_ITEM: 'MAX_ALLOWED_QUANTITY_VALUE_EXCEEDED_FOR_ITEM',

  NOT_VAS_ITEM: 'NOT_VAS_ITEM',
  PARENT_ITEM_NOT_DEFAULT_ITEM: 'PARENT_ITEM_NOT_DEFAULT_ITEM',

  UNEXPECTED_ITEM_FOUND: 'UNEXPECTED_ITEM_FOUND',
  UNEXPECTED_ITEM_FOUND_IT_LOOKS_LIKE_VAS: 'UNEXPECTED_ITEM_FOUND_IT_LOOKS_LIKE_VAS',

  VAS_ITEM_NOT_ADDED_PRICE_IS_HEIGHER_THAN_PARENT: 'VAS_ITEM_NOT_ADDED_PRICE_IS_HEIGHER_THAN_PARENT',
  VAS_ITEM_NOT_ADDED_PARENT_NOT_FOUND: 'VAS_ITEM_NOT_ADDED_PARENT_NOT_FOUND',
  VAS_ITEM_NOT_ADDED_PARENT_DEFAULT_ITEM_DOES_NOT_EXPECT_VAS_ITEM:
    'VAS_ITEM_NOT_ADDED_PARENT_DEFAULT_ITEM_DOES_NOT_EXPECT_VAS_ITEM',
};
