package com.feyz.checkoutcase.app.message;

public class ErrorMessage {
    public static final String ADD_ITEM_BASE_ERROR = "ADD_ITEM_BASE_ERROR";
    public static final String MAX_DIGITAL_ITEM_EXCEED_ERROR = "MAX_DIGITAL_ITEM_EXCEED_ERROR";
    public static final String MAX_UNIQUE_ITEM_EXCEED_ITEM_ERROR = "MAX_UNIQUE_ITEM_EXCEED_ITEM_ERROR";

    public static final String MAX_QUANTITY_VALUE_EXCEEDED_FOR_THE_ACTUAL_ITEM = "MAX_QUANTITY_VALUE_EXCEEDED_FOR_THE_ACTUAL_ITEM";
    public static final String MAX_QUANTITY_VALUE_EXCEEDED_IN_CART = "MAX_QUANTITY_VALUE_EXCEEDED_IN_CART";
    public static final String MAX_VAS_ITEM_QUANTITY_VALUE_EXCEEDED_IN_CART = "MAX_VAS_ITEM_QUANTITY_VALUE_EXCEEDED_IN_CART";
    public static final String MAX_AMOUNT_EXCEEDED_IN_CART = "MAX_AMOUNT_EXCEEDED_IN_CART";

    public static final String DEFAULT_ITEM_NOT_FOUND_FOR_VAS_ITEM = "DEFAULT_ITEM_NOT_FOUND_FOR_VAS_ITEM";
    public static final String DEFAULT_ITEM_DISABLED_FOR_VAS_ITEM = "DEFAULT_ITEM_DISABLED_FOR_VAS_ITEM";
    public static final String DEFAULT_ITEM_CANT_BE_LOWER_THAN_VAS_ITEM_PRICE = "DEFAULT_ITEM_CANT_BE_LOWER_THAN_VAS_ITEM_PRICE";
    public static final String DEFAULT_ITEM_MOSTLY_HAVE_3_VAS_ITEM = "DEFAULT_ITEM_MOSTLY_HAVE_3_VAS_ITEM";

    public static final String ITEM_NOT_FOUND_TO_REMOVE = "ITEM_NOT_FOUND_TO_REMOVE";

    public static final String NOT_A_VAS_ITEM = "NOT_A_VAS_ITEM";
}
